### ISSUE TITLE
Can't get it to work.

### ISSUE THREAD

**Issue by Aoi-chan** [majestrate/oniichan#1]
I'm trying to run this so I can use as a reference for my own project, but I can't get it working. The first problem I identified is that the program can't create a database at the specified location. You might want to change this line [0] to a relative path inside the project directory. I got around this by creating /var/lib/oniichan manually, but I still get a 404 when trying to access the site through localhost.

[0] https://github.com/majestrate/oniichan/blob/master/oniichan/db.py#L13

**Comment by majestrate** [comment]
wow i forgot i had this project, let me refresh myself on what how this code works.

**Comment by majestrate** [comment]
looks like i have some uncommitted changes from 2 years ago that may fix this, verifying...

**Comment by majestrate** [comment]
Okay from what I remember this application generates html pages and hides behind a reverse proxy while the main webserver serves the generated files. the directories for each are hard coded... ew @~@

**Comment by Aoi-chan** [comment]
Thanks for the speedy response. I hope I'm not troubling you too much.

**Comment by majestrate** [comment]
I'll see if I can fix this up a bit tomorrow

**Comment by majestrate** [comment]
as of 497d741 , the repo should contain sufficient docs for dev and prod setups with some additions fixes in the mod panel + initial setup

**Comment by majestrate** [comment]
rather, commit c760175c8eafd69ceb2bd018d6bf2c61d3076dea

**Comment by Aoi-chan** [comment]
Awesome. Thank you very much.
